### ISSUE TITLE
firebase 4.8.0 / 4.8.1 types

### ISSUE THREAD

**Issue by nrodriguezm** [hamzaavvan/event-management-ionic#2]
Hi, did you roll back @javebratt PR?

I see this commit undoing the changes:

https://github.com/hamzaavvan/event-management-ionic/commit/11ea3bddef3b9c4ccff1f7ad45d6f9d107b4aff1

Thanks for the work done!

**Comment by nrodriguezm** [comment]
Tried current master and got the error:

Cannot find module '@firebase/database'.
in: src/providers/profile/profile.ts

import { Reference } from '@firebase/database';

**Comment by hamzaavvan** [comment]
Yes, we did a rollback. I hope everything will be fine now.
